### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by XvXvXvXvX** [useragents/Instagram-Username-Auto-Claimer#28]
Traceback (most recent call last):
  File "/home/kali/Instagram-Username-Auto-Claimer-main/claim.py", line 199, in <module>
    obj.main()
  File "/home/kali/Instagram-Username-Auto-Claimer-main/claim.py", line 183, in main
    email_address, name = self.get_email(csrf_token)
  File "/home/kali/Instagram-Username-Auto-Claimer-main/claim.py", line 112, in get_email
    email = r.text.split('"email":"')[1].split('"')[0]
IndexError: list index out of range

**Comment by Kenterum** [comment]
I have the same issue. Trying to understand why

**Comment by MahmoudGamalElDeen** [comment]
Traceback (most recent call last):
File "/home/kali/Instagram-Username-Auto-Claimer-main/claim.py", line 199, in
obj.main()
File "/home/kali/Instagram-Username-Auto-Claimer-main/claim.py", line 183, in main
email_address, name = self.get_email(csrf_token)
File "/home/kali/Instagram-Username-Auto-Claimer-main/claim.py", line 112, in get_email
email = r.text.split('"email":"')[1].split('"')[0]
IndexError: list index out of range

any solution ?

**Comment by useragents** [comment]
Fixed
